//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.14 at 08:47:58 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://vodafone.com/getInvoiceList", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.vodafone.getinvoicelist;
